### ISSUE TITLE
wtfapp-devenv: Build failed with an exception

### ISSUE THREAD

**Issue by gmacario** [gmacario/wtf-docs#14]
Logged as ubuntu@aws-wtf

```
$ cd ~/UdooWtf && docker run -ti -v $(pwd):/opt/workspace gmacario/wtfapp-devenv
```

Now logged as root@container

```
root@fba51a289c8a:/opt/workspace# ./gradlew 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> failed to find Build Tools revision 23.0.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.482 secs
root@fba51a289c8a:/opt/workspace#
```

**Comment by gmacario** [comment]
Reference: http://developer.android.com/guide/topics/manifest/uses-sdk-element.html#ApiLevels

**Comment by gmacario** [comment]
File `build.gradle` and `buildToolsVersion` are documented in http://developer.android.com/tools/revisions/build-tools.html

**Comment by gmacario** [comment]
Testing with https://github.com/gmacario/colorcode

```
$ cd && git clone https://github.com/gmacario/colorcode
$ cd colorcode && docker run -ti -v $(pwd):/opt/workspace gmacario/wtfapp-devenv
```

Same result as before:

```
...
Download https://jcenter.bintray.com/org/abego/treelayout/org.abego.treelayout.core/1.0.1/org.abego.treelayout.core-1.0.1.jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> failed to find target with hash string 'android-23' in: /opt/android-sdk-linux

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 39.712 secs
root@9b162ea9d8f4:/opt/workspace#
```

WTF (this original one...)

**Comment by gmacario** [comment]
TODO: Understand effect of
- https://github.com/gmacario/wtf-docs/blob/master/wtfapp-devenv/Dockerfile#L16
- https://github.com/gmacario/wtf-docs/blob/master/wtfapp-devenv/Dockerfile#L25

See also: http://tools.android.com/recent/updatingsdkfromcommand-line

**Comment by gmacario** [comment]
Just as a test (IT WILL INSTALL A LOT OF STUFF) type the following as root@container

```
$ android list sdk
$ android update sdk --no-ui
$ ls -la /opt/android-sdk-linux/
$ ./gradlew
```

Result: Still failing...

```
root@9b162ea9d8f4:/opt/workspace# ./gradlew 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> failed to find Build Tools revision 23.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.925 secs
root@9b162ea9d8f4:/opt/workspace#
```

**Comment by gmacario** [comment]
See this blog post: http://ainoya.io/docker-android-walter

See also some similar Dockerfiles:
- https://github.com/gfx/docker-android-project/blob/master/Dockerfile
- https://github.com/ainoya/docker-android-project/blob/master/Dockerfile

**Comment by WillyShakes** [comment]
I read the blog post , your dockerfile seems to be correct.

**Comment by gmacario** [comment]
[Hackathon Droidcon Italy 2017](http://it.droidcon.com/2017/hackathon-droidcon-italy/) took place and some of the original WTF team members decided to create another team.

I am closing this issue as I understand the WTF project has no future.
