### ISSUE TITLE
Develop WTF Application v2.0

### ISSUE THREAD

**Issue by gmacario** [gmacario/wtf-docs#16]

**Comment by WillyShakes** [comment]
What is missing for this Milestone ?

**Comment by gmacario** [comment]
> What is missing for this Milestone ?

According to https://github.com/gmacario/wtf-docs

> - [ ] Create the model class devices and the database (CRUD metods)
> - [ ] Create a class to read a digital input on the UDOO NEO hardware (or from IoTSemplice?)
> - [ ] Create an activity to test the first use case
> - [ ] Add the Google Calendar API (@umbho)

And -- of course -- https://github.com/gmacario/wtf-docs/issues/6

But now you probably know much better than myself :-)

**Comment by gmacario** [comment]
[Hackathon Droidcon Italy 2017](http://it.droidcon.com/2017/hackathon-droidcon-italy/) took place and some of the original WTF team members decided to create another team.

I am closing this issue as I understand the WTF project has no future.
