### ISSUE TITLE
README.md: Add project logo

### ISSUE THREAD

**Issue by gmacario** [gmacario/wtf-docs#18]

**Comment by WillyShakes** [comment]
Refer to this proposition: https://github.com/gmacario/wtf-docs/pull/23

**Comment by gmacario** [comment]
Close via PR https://github.com/gmacario/wtf-docs/pull/23

**Comment by gmacario** [comment]
@WillyShakes I believe you may now safely remove branch `WillyShakes-logo-issue` from https://github.com/gmacario/wtf-docs/branches
