### ISSUE TITLE
WTF-Aperitive @lobelix, 2016-04-14 18:30

### ISSUE THREAD

**Issue by gmacario** [gmacario/wtf-docs#21]
From @WillyShakes on [Gitter.im](https://gitter.im/gmacario/wtf-docs), 2016-04-12 00:41

> Ciao ragazzi per festeggiare la vittoria, pensavamo di organizzare un aperitivo questa settimana dopo le 6 in centro.
> Possiamo farlo Venerdì / 18:30 al Mixto.
> Fatemi sapere se ci siete cosi magari chiamo per prenotare.

**IMPORTANT**: If (1) you want to come and (2) the proposed date/time(s) do not work for you, please propose another

Update from @WillyShakes on [Gitter.im](https://gitter.im/gmacario/wtf-docs), 2016-04-13 12:31

> Prenotato lobelix per domani alle 18:30  
> indirizzo : Piazza Savoia, 4, 10122 Torino

Confirmed participants so far:

| Firstname | Lastname | GitHub | Attend? | Notes |
| --- | --- | --- | --- | --- |
| Alessandro | Censi | [AleDroid93](https://github.com/AleDroid93) | ? | ? |
| Gianpaolo | Macario | [gmacario](https://github.com/gmacario) | Maybe | Must juggle private schedule |
| Paolo | Marino | [dolcestilnuovo65](https://github.com/dolcestilnuovo65) | ? | ? |
| Wilfried | Mbouenda Mbogne | [WillyShakes](https://github.com/WillyShakes) | YES | ? |
| Alessandro | Morelli | [AlessandroMorelli96](https://github.com/AlessandroMorelli96) | ? | ? |
| Giuseppe | Nesca | [neskov7](https://github.com/neskov7) | ? | ? |
| Umberto | Pepato | [umbHo](https://github.com/umbHo) | ? | ? |
| Adam | Szewera | [adamszewe](https://github.com/adamszewe) | ? | ? |
| Alessandro | Szewera | [AlessandroBDP](https://github.com/AlessandroBDP) | ? | ? |

**Comment by dolcestilnuovo65** [comment]
Io venerdi sera vado all'open night dell'hackathon sul food, non si potrebbe spostare li i festeggiamenti?

https://www.eventbrite.it/e/biglietti-from-farm-to-fork-food-hackathon-21385537719

**Comment by gmacario** [comment]
Ciao,

Purtroppo non sono riuscito a cambiare alcuni impegni di famiglia gia' presi in precedenza per cui non ce la faccio a passare dal http://www.lobelixcafe.com/ stasera.

Anche stavolta saro' con voi solo virtualmente - se vi va durante l'aperitivo aggiornatemi/ci (scrivendo cose non confidenziali, per carita') su https://gitter.im/gmacario/wtf-docs

Ci rivediamo comunque alla prossima occasione, fidatevi!

**Comment by dolcestilnuovo65** [comment]
Ci contiamo Gianpaolo

**Comment by gmacario** [comment]
:+1:
