### ISSUE TITLE
Shall we switch from Gitter to Telegram?

### ISSUE THREAD

**Issue by gmacario** [gmacario/wtf-docs#22]
From @neskov7 on https://gitter.im/gmacario/wtf-docs, 2016-04-12

> ragazzi ma che ne dite di un supergruppo Telegram? Secondo me è molto più comodo

**Comment by gmacario** [comment]
@neskov7: Please define "e' molto piu' comodo" and elaborate on which use cases you believe Telegram may support which Gitter does not

**Comment by giuseppe-nesca** [comment]
È più comodo in tutti i casi in cui non si tratta di coding. Molto più maneggevole e accessibile dato che tutti lo hanno sullo smartphone e lo usano durante la giornata già frequentemente. Poi penso che riservare Gitter (che è molto invasivo a giudicare da tutte le email di notifica che mi arrivano) per un utilizzo esclusivamente di lavoro mentre per organizzare un incontro , o un aperitivo in questo caso , usare telegram sia una soluzione efficiente

**Comment by WillyShakes** [comment]
gitter.im ha un anche un' app mobile volendo uno lo scarica.

**Comment by giuseppe-nesca** [comment]
Sul tablet già provveduto, ma ho problemi di memoria sullo smartphone... Vedrò di ricavare  un po' di spazio

**Comment by gmacario** [comment]
Ribadisco: La scelta di gitter.im come chat per https://github.com/gmacario/wtf-docs nasce dall'uso della chat prevalentemente legato al progetto (coding).

Per tutto il resto c'e' il mondo: Telegram, Whatsapp, Skype, IRC, Pidgin, Jabber e chi piu' ne ha piu' ne metta (ho citato solo i programmi che ho installato sul mio PC e utilizzo quotidianamente).

Closing issue

**Comment by gmacario** [comment]
@neskov7 

> ... Gitter (che è molto invasivo a giudicare da tutte le email di notifica che mi arrivano)

Le notifiche sono configurabili: Clicca in alto a destra su "Room settings" > "Notifications"

A me le email arrivano solo quando non ho una pagina del browser aperta su https://gitter.im/

Per saperne di piu': http://lmgtfy.com/?q=gitter+notifications

**Comment by giuseppe-nesca** [comment]
Ho approfondito gitter e non posso che essere d'accordo con te. Il mio intento era più che altro limitare l'utilizzo per il coding  e utilizzare Telegram per tutto il resto (ad esempio per organizzare i vari incontri)

**Comment by gmacario** [comment]
Tutto e' bene quel che finisce bene...

Buona notte!

**Comment by giuseppe-nesca** [comment]
Del resto il problem solving è la nostra competenza più importante  ;)
Buona notte!
